version: '3.8'

services:
  mininet:
    build: .
    container_name: mininet-experiment
    privileged: true
    network_mode: host
    volumes:
      - ./network_topology:/root/network_topology
      - ./scripts:/root/scripts
      - ./results:/root/results
    stdin_open: true
    tty: true
    command: /bin/bash
